# -*- coding: utf-8 -*-
"""
Generated by ArcGIS ModelBuilder on : 2025-02-11 15:20:50
"""
import arcpy
from sys import argv

#For inline variable substitution, parameters passed as a String are evaluated using locals(), globals() and isinstance(). To override, substitute values directly.
def GdbsToFds():  # GDBs To Feature Dataset

    # To allow overwriting outputs change overwriteOutput option to True.
    arcpy.env.overwriteOutput = False

    # Model Environment settings
    with arcpy.EnvManager(scratchWorkspace="C:\\acCS\\gis4207_prog\\week_06\\lab\\gis4207-week06\\AppData\\Local\\Temp\\ArcGISProTemp23072\\47ee5f44-6f3c-41a1-8c6c-f605bb5859c8\\Default.gdb", workspace="C:\\acCS\\gis4207_prog\\week_06\\lab\\gis4207-week06\\AppData\\Local\\Temp\\ArcGISProTemp23072\\47ee5f44-6f3c-41a1-8c6c-f605bb5859c8\\Default.gdb"):
        elementary_school_catchments = "A:\\Winter2021\\GIS4211\\Assessments\\A1\\01_SourceData\\Elementary_School_Catchments_GDB\\elementary_school_catchments.gdb\\elementary_school_catchments"
        _02_Working_Folder_for_Geodatabase = "A:\\Winter2021\\GIS4211\\Assessments\\A1\\02_Working"
        parks = "A:\\Winter2021\\GIS4211\\Assessments\\A1\\01_SourceData\\parks_GDB\\parks.gdb\\parks"
        road_centrelines = "A:\\Winter2021\\GIS4211\\Assessments\\A1\\01_SourceData\\Road_Centrelines_GDB\\road_centrelines.gdb\\road_centrelines"
        Schools = "A:\\Winter2021\\GIS4211\\Assessments\\A1\\01_SourceData\\Schools_GDB\\schools.gdb\\Schools"
        surrey_city_boundary = "A:\\Winter2021\\GIS4211\\Assessments\\A1\\01_SourceData\\surrey_city_boundary_gdb\\surrey_city_boundary.gdb\\surrey_city_boundary"

        # Process: Create File Geodatabase (Create File Geodatabase) (management)
        with arcpy.EnvManager(scratchWorkspace="C:\\Users\\dimayuj\\AppData\\Local\\Temp\\ArcGISProTemp23072\\47ee5f44-6f3c-41a1-8c6c-f605bb5859c8\\Default.gdb", workspace="C:\\Users\\dimayuj\\AppData\\Local\\Temp\\ArcGISProTemp23072\\47ee5f44-6f3c-41a1-8c6c-f605bb5859c8\\Default.gdb"):
            Surrey_Working_gdb = arcpy.management.CreateFileGDB(out_folder_path=_02_Working_Folder_for_Geodatabase, out_name="Surrey_Working")[0]

        # Process: Create Feature Dataset (Create Feature Dataset) (management)
        with arcpy.EnvManager(scratchWorkspace="C:\\Users\\dimayuj\\AppData\\Local\\Temp\\ArcGISProTemp23072\\47ee5f44-6f3c-41a1-8c6c-f605bb5859c8\\Default.gdb", workspace="C:\\Users\\dimayuj\\AppData\\Local\\Temp\\ArcGISProTemp23072\\47ee5f44-6f3c-41a1-8c6c-f605bb5859c8\\Default.gdb"):
            UTMZone10 = arcpy.management.CreateFeatureDataset(out_dataset_path=Surrey_Working_gdb, out_name="UTMZone10", spatial_reference="PROJCS[\"NAD_1983_UTM_Zone_10N\",GEOGCS[\"GCS_North_American_1983\",DATUM[\"D_North_American_1983\",SPHEROID[\"GRS_1980\",6378137.0,298.257222101]],PRIMEM[\"Greenwich\",0.0],UNIT[\"Degree\",0.0174532925199433]],PROJECTION[\"Transverse_Mercator\"],PARAMETER[\"False_Easting\",500000.0],PARAMETER[\"False_Northing\",0.0],PARAMETER[\"Central_Meridian\",-123.0],PARAMETER[\"Scale_Factor\",0.9996],PARAMETER[\"Latitude_Of_Origin\",0.0],UNIT[\"Meter\",1.0]];-5120900 -9998100 10000;-100000 10000;-100000 10000;0.001;0.001;0.001;IsHighPrecision")[0]

        # Process: Convert School Catchments to UTM Zone 10 (Feature Class To Feature Class) (conversion)
        with arcpy.EnvManager(scratchWorkspace="C:\\Users\\dimayuj\\AppData\\Local\\Temp\\ArcGISProTemp23072\\47ee5f44-6f3c-41a1-8c6c-f605bb5859c8\\Default.gdb", workspace="C:\\Users\\dimayuj\\AppData\\Local\\Temp\\ArcGISProTemp23072\\47ee5f44-6f3c-41a1-8c6c-f605bb5859c8\\Default.gdb"):
            elementary_school_catchments_projected = arcpy.conversion.FeatureClassToFeatureClass(in_features=elementary_school_catchments, out_path=UTMZone10.__str__().format(**locals(),**globals())if isinstance(UTMZone10, str) else UTMZone10, out_name="elementary_school_catchments")[0]

        # Process: Convert Parks to UTM Zone 10 (Feature Class To Feature Class) (conversion)
        with arcpy.EnvManager(scratchWorkspace="C:\\Users\\dimayuj\\AppData\\Local\\Temp\\ArcGISProTemp23072\\47ee5f44-6f3c-41a1-8c6c-f605bb5859c8\\Default.gdb", workspace="C:\\Users\\dimayuj\\AppData\\Local\\Temp\\ArcGISProTemp23072\\47ee5f44-6f3c-41a1-8c6c-f605bb5859c8\\Default.gdb"):
            parks_projected = arcpy.conversion.FeatureClassToFeatureClass(in_features=parks, out_path=UTMZone10.__str__().format(**locals(),**globals())if isinstance(UTMZone10, str) else UTMZone10, out_name="parks")[0]

        # Process: Convert Roads to UTM Zone 10 (Feature Class To Feature Class) (conversion)
        with arcpy.EnvManager(scratchWorkspace="C:\\Users\\dimayuj\\AppData\\Local\\Temp\\ArcGISProTemp23072\\47ee5f44-6f3c-41a1-8c6c-f605bb5859c8\\Default.gdb", workspace="C:\\Users\\dimayuj\\AppData\\Local\\Temp\\ArcGISProTemp23072\\47ee5f44-6f3c-41a1-8c6c-f605bb5859c8\\Default.gdb"):
            road_centrelines_projected = arcpy.conversion.FeatureClassToFeatureClass(in_features=road_centrelines, out_path=UTMZone10.__str__().format(**locals(),**globals())if isinstance(UTMZone10, str) else UTMZone10, out_name="road_centrelines")[0]

        # Process: Convert Schools to UTM Zone 10 (Feature Class To Feature Class) (conversion)
        with arcpy.EnvManager(scratchWorkspace="C:\\Users\\dimayuj\\AppData\\Local\\Temp\\ArcGISProTemp23072\\47ee5f44-6f3c-41a1-8c6c-f605bb5859c8\\Default.gdb", workspace="C:\\Users\\dimayuj\\AppData\\Local\\Temp\\ArcGISProTemp23072\\47ee5f44-6f3c-41a1-8c6c-f605bb5859c8\\Default.gdb"):
            Schools_projected = arcpy.conversion.FeatureClassToFeatureClass(in_features=Schools, out_path=UTMZone10.__str__().format(**locals(),**globals())if isinstance(UTMZone10, str) else UTMZone10, out_name="schools")[0]

        # Process: Convert City Boundary to UTM Zone 10 (Feature Class To Feature Class) (conversion)
        with arcpy.EnvManager(scratchWorkspace="C:\\Users\\dimayuj\\AppData\\Local\\Temp\\ArcGISProTemp23072\\47ee5f44-6f3c-41a1-8c6c-f605bb5859c8\\Default.gdb", workspace="C:\\Users\\dimayuj\\AppData\\Local\\Temp\\ArcGISProTemp23072\\47ee5f44-6f3c-41a1-8c6c-f605bb5859c8\\Default.gdb"):
            surrey_city_boundary_projected = arcpy.conversion.FeatureClassToFeatureClass(in_features=surrey_city_boundary, out_path=UTMZone10.__str__().format(**locals(),**globals())if isinstance(UTMZone10, str) else UTMZone10, out_name="surrey_city_boundary")[0]

        return UTMZone10

if __name__ == '__main__':
    GdbsToFds(*argv[1:])
